from pydantic import BaseModel, Field
from typing import List, Dict, Any

class AgentRequest(BaseModel):
    """Model for the incoming agent request."""
    request: str = Field(
        ..., 
        min_length=1, 
        max_length=2000, 
        description="The natural language request for the agent."
    )

class AgentResponse(BaseModel):
    """Model for the agent's response."""
    plan: List[Dict[str, Any]] = Field(..., description="The task list/plan generated by the agent.")
    execution_log: List[Dict[str, Any]] = Field(..., description="The execution log of each step in the plan.")
    document_path: str = Field(..., description="The path to the generated .docx file.")
    plan_source: str = Field(..., description="Source of the plan: 'llm' or 'fallback'.")
    assumptions: List[str] = Field(default_factory=list, description="Explicit assumptions made by the agent.")
